server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "mysql"
          host: _HOST_
          port: 3306
          database: temporal
          user: _USERNAME_
          password: _PASSWORD_

      visibility:
        driver: "sql"

        sql:
          driver: "mysql"
          host: _HOST_
          port: 3306
          database: temporal_visibility
          user: _USERNAME_
          password: _PASSWORD_

cassandra:
  enabled: false

mysql:
  enabled: true

schema:
  setup:
    enabled: false
  update:
    enabled: false
